### ISSUE TITLE
Failed to download Chromium r508693! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by jinxin479** [FormidableLabs/spectacle-boilerplate#64]
RROR: Failed to download Chromium r508693! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: connect ETIMEDOUT 119.28.102.126:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '119.28.102.126',
  port: 443 }
npm WARN spectacle-boilerplate@1.0.1 No repository field.

**Comment by sagarwasule** [comment]
@jinxin479  I'm also receiving the same error. How did you fixed this ?
